# Generated by Django 6.0 on 2026-01-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Если клички нет - оставьте пустым', max_length=100, verbose_name='Кличка')),
                ('species', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака')], max_length=10, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, help_text='Не обязательно', max_length=100, verbose_name='Порода')),
                ('age', models.IntegerField(help_text='Примерный возраст', verbose_name='Возраст (лет)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('child_friendly', models.IntegerField(default=5, help_text='От 1 (агрессивен) до 10 (очень дружелюбен)', verbose_name='Дружелюбие к детям')),
                ('other_pet_friendly', models.IntegerField(default=5, help_text='От 1 до 10', verbose_name='Отношение к другим животным')),
                ('activity_level', models.IntegerField(default=5, help_text='От 1 (спокойный) до 10 (очень активный)', verbose_name='Уровень активности')),
                ('size_category', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный')], default='medium', max_length=10, verbose_name='Размер')),
                ('arrival_date', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
                ('is_available', models.BooleanField(default=True, verbose_name='Ищет дом')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название приюта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, help_text='Расскажите о себе и условиях содержания', verbose_name='Сообщение')),
                ('compatibility_score', models.FloatField(default=0.0, verbose_name='Процент совместимости')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal', verbose_name='Животное')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.shelter', verbose_name='Приют'),
        ),
    ]
